---
abstract: 'Event Repository'
author:
  - 'Lauren O''Meara'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Osgood-Server
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::REST: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Params::Nested: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.7011
  DBIx::Class::TimeStamp: 0
  DateTime: 0
  DateTime::Format::DBI: 0
  JSON::XS: 0
  Osgood::Client: 2.0.0
  YAML: 0
version: 2.0.0
